# -*- coding: utf-8 -*-
"""adventure

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qPydqfUd3gWb18VgVSNqFVV0poMzQNo0
"""

# Introduction
print("Welcome to the Adventure Game!")

print(" ")

print("You are an explorer searching for a legendary treasure on a mysterious island.")

print(" ")

print("You arrive on the beach by boat.")

print(" ")

print("What will you do first?")

print(" ")

# First Phase
def phase_one():
    print("Path A - Return to the boat and leave, Path B - Enter the forest, Path C - Walk along the beach.")
    print(" ")

    choice1 = input("Enter the letter of your choice, A, B, or C: \n").lower()

    print(" ")

    if choice1 == "a":
        print("You decided to return to the boat and leave.")
        print(" ")
        print("Wrong path! Game over.")

    elif choice1 == "b":
        print("You decided to enter the forest.")
        print(" ")
        print("You chose the right path! Advancing to the next phase...\n")
        phase_forest2()  # Call the next forest phase

    elif choice1 == "c":
        print("You decided to walk along the beach.")
        print(" ")
        print("You chose the right path! Advancing to the next phase...\n")
        phase_beach2()  # Call the next beach phase

    else:
        print("Invalid choice! Try again.")
        phase_one()  # Restart the phase if the choice is invalid

# Forest Phase (expanding the story)
def phase_forest2():
    print("You are now in the dense forest. You hear strange sounds in the distance...")
    print(" ")
    print("Path A - Leave the forest and return to the beach, Path B - Check what's making the strange sounds, Path C - Hide behind a tree.")
    print(" ")
    choice2 = input("Enter the letter of your choice, A, B, or C: \n").lower()

    if choice2 == "a":
        print("You decided to return to the beach.")
        print(" ")
        print("You chose the right path! Advancing to the next phase...\n")
        phase_beach2()

    elif choice2 == "b":
        print("You decided to check what's making the strange sounds.")
        print(" ")
        print("It was a jaguar and it attacked you! Wrong path! Game over.")

    elif choice2 == "c":
        print("You decided to hide behind a tree.")
        print(" ")
        print("You didn't notice the snake and it bit you! Wrong path! Game over.")

    else:
        print("Invalid choice! Try again.")
        phase_forest2()

# Beach Phase (expanding the story)
def phase_beach2():
    print("You are walking along the beach and notice something shiny in the sand.")
    print(" ")
    print("Path A - Check the shiny object in the sand, Path B - Ignore the shiny object and keep walking, Path C - Enter the forest.")
    print(" ")

    choice3 = input("Enter the letter of your choice, A, B, or C: \n").lower()

    if choice3 == "a":
        print("You decided to check the shiny object in the sand.")
        print(" ")
        print("You chose the right path! Congratulations, you found the legendary treasure!")
        print(" ")
        print("Thank you for playing!")

    elif choice3 == "b":
        print("You decided to ignore the shiny object and keep walking.")
        print(" ")
        print("Nothing happened!")
        phase_beach2()

    elif choice3 == "c":
        print("You decided to enter the forest.")
        print(" ")
        print("You chose the right path! Advancing to the next phase...\n")
        phase_forest2()

    else:
        print("Invalid choice! Try again.")
        phase_beach2()

# Start of the game
phase_one()